version: '2'

services:
  tasker:
    image: strm/tasker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      configuration: |
        logging:
          level:
            ROOT: DEBUG
            org.springframework.web: DEBUG
            sh.strm: DEBUG
        schedule:
          - every: hour
            task: blink
        tasks:
          docker:
            - name: blink
              image: blink-img:latest
              # volumes:
              #   - /Users/apeters/apps/blink/secrets:/usr/src/secrets
              script:
                - node index.js

  # blink:
  #   build: .
  #   image: blink-img:latest
  #   restart: always
  #   volumes:
  #     - .:/usr/src/app
